src/apps/proposal/urls.py
from django.urls import path
from . import views

app_name = "proposal"


warehouse_urls = [
    path("warehouse_list", views.WarehouseList.as_view(), name="warehouse_list"),
    path("warehouse_products", views.WarehouseProducts.as_view(), name="warehouse_products"),
    path("user_list", views.UserList.as_view(), name="user_list"),
    path("order_list", views.OrderList.as_view(), name="order_list"),
    path("recurring_order", views.RecurringOrder.as_view(), name="recurring_order"),
    path("order", views.Order.as_view(), name="order"),
    path("return_order", views.ReturnOrder.as_view(), name="return_order"),
    path("express_delivery", views.ExpressDelivery.as_view(), name="express_delivery"),
    path("delivery_list", views.Delivery.as_view(), name="delivery_list"),
]

urlpatterns = [
    #     path("", views.LoginView.as_view(), name="login"),

    path("dashboard", views.Dashboard.as_view(), name="dashboard"),
    path("proposal-list", views.ProposalList.as_view(), name="proposal_list"),
    path("proposal-preview", views.ProposalPreview.as_view(),
         name="proposal_preview"),
    path("opportunity-list", views.OpportunityList.as_view(),
         name="opportunity_list"),
    path("opportunity-details", views.OpportunityDetails.as_view(),
         name="opportunity_details"),
    path("home", views.Home.as_view(), name="home"),
    path("opportunity", views.Opportunity.as_view(), name="opportunity"),
    path("generate_estimate_table", views.GenerateEstimateTable.as_view(),
         name="generate_estimate_table"),
    path("material-list", views.MaterialListView.as_view(), name="material_list"),
    path("glue-material-list", views.GlueListView.as_view(),
         name="glue_material_list"),
    path("final-ready-material-list", views.FinalReadyMaterialListView.as_view(),
         name="final_ready_material_list"),
    path("estimate", views.EstimateView.as_view(), name="estimate"),
    path("proposal", views.ProposalView.as_view(), name="proposal"),
    path("proposal-creation", views.ProposalCreateView.as_view(),
         name="proposal-creation"),
    path("products", views.ProductList.as_view(), name="product_list"),
    path("labor-cost", views.LaborCostList.as_view(), name="labor_cost_list"),
    path("customer", views.CustomerList.as_view(), name="customer_list"),
    path("task", views.TaskList.as_view(), name="task_list"),
    path("vendor", views.VendorList.as_view(), name="vendor_list"),
    path("inbox", views.InboxList.as_view(), name="inbox_list"),
    path("update_profile", views.UpdateProfile.as_view(), name="update_profile"),
    path("motor_fla_calculator", views.MotorFLACalculator.as_view(),
         name="motor_fla_calculator"),
    path("pump_flo_calculator", views.PumpFLOCalculator.as_view(), name="pump_flo_calculator"),
    path("netafim_calculator", views.NetafimCalculator.as_view(), name="netafim_calculator"),
    path("overlap_pro_calculator", views.OverlapProCalculator.as_view(),
         name="overlap_pro_calculator"),
    path("southwire_calculator", views.SouthwireCalculator.as_view(),
         name="southwire_calculator"),
    path("paigewire_calculator", views.PaigewireCalculator.as_view(),
         name="paigewire_calculator"),
    path("choose_screens", views.ChooseScreens.as_view(), name="choose_screens"),
    path("coming_soon", views.ComingSoon.as_view(), name="coming_soon"),
]+warehouse_urls

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.proposal.urls", 'proposal'), namespace="proposal")),
    path("", include(("apps.user.urls", 'user'), namespace="user")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/v1/", include("core.api_router")),
]

src/templates/warehouse/comment_table.html
<div class="table-responsive mt-3">
  <table class="table table-striped table-bordered zero-configuration">
    <thead>
      <tr class="text-center">
        <th style="width: 25% !important">Documents</th>
        <th style="width: 25% !important">Created at</th>
        <th>Comments</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div style="margin-top: 20px">
            <a
              href="#"
              class="d-flex"
              style="font-size: 16px; justify-content: center"
              ><span>File1</span>
              <div style="margin-top: 2px; margin-left: 5px">
                <i class="icon-cloud-download"></i>
              </div>
            </a>
          </div>
        </td>
        <td>
          <div
            class="d-flex"
            style="font-size: 16px; justify-content: center; margin-top: 20px"
          >
            <span>20-05-2024</span>
          </div>
        </td>
        <td>
          Farming pumps and pipes are indispensable tools, ensuring efficient
          irrigation and water management. They're the lifeline of agriculture,
          delivering sustenance to crops, fostering growth, and...
          <a href="#" class="read-more">Read More</a>
        </td>
        <div
          class="modal fade text-left"
          id="inlineComment"
          tabindex="-1"
          role="dialog"
          aria-labelledby="myModalLabel33"
          aria-hidden="true"
          data-backdrop="false"
        >
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel5">Comments</h4>
                <hr />
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true"
                    ><i class="ft-x font-medium-2 text-bold-700"></i
                  ></span>
                </button>
              </div>
              <div class="modal-body">
                <div class="form-group">
                  <div class="custom-file">
                    <p>
                      Farming pumps and pipes are indispensable tools, ensuring
                      efficient irrigation and water management. They're the
                      lifeline of agriculture, delivering sustenance to crops,
                      fostering growth, and maximizing yield. Essential
                      equipment for modern farming practices.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </tr>
    </tbody>
  </table>
</div>

src/templates/warehouse/create_delivery.html
<div class="card-header">
  <div class="float-right">
    <div
      class="modal fade text-left"
      id="create_delivery"
      tabindex="-1"
      role="dialog"
      aria-labelledby="myModalLabel33"
      aria-hidden="true"
      data-backdrop="false"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Create Order Delivery</h4>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true"
                ><i class="ft-x font-medium-2 text-bold-700"></i
              ></span>
            </button>
          </div>
          <form action="#">
            <div class="modal-body">
              <div class="row">
                <div class="col">
                  <label>Customer: </label>
                  <div class="form-group">
                    <input
                      type="text"
                      placeholder="Customer"
                      class="form-control"
                    />
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <label>Delivery Location: </label>
                  <div class="form-group">
                    <input
                      type="text"
                      placeholder="Delivery Location"
                      class="form-control"
                    />
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <label>Order: </label>
                  <input 
                  type="text" 
                  class="form-control"
                  placeholder="Order ID"
                  >
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <label>Select Product</label>
                  <fieldset class="form-group">
                      <select class="form-control" id="countrySelect" multiple>
                          <option selected="selected">COMPANION FLG GALV 4" FLGXFPT</option>
                          <option>METAL FITTINGS</option>
                          <option selected="selected">MISTER BLU NOZZEL W/ CHECK VALVE NETAFIM VIBRONET	</option>
                          <option>SN BL10.6GPH STK30" LD LRSS	</option>
                          <option>SN HEAD 7.4GPH LT-GRN W/DFLT	</option>
                          <option>SN PC HEAD 18.5GPH BLU W/DFLTR	</option>
                          <option selected="selected">SN PC HEAD LT GRN LR W/DFLTR	</option>
                          <option>SN PRP SWVL LR ORG NZ W/30" ST	</option>
                          <option>SUPERNET PC 7.5GPH LR</option>
                          <option>VIBRONET BLU SPK 10.4GPH CV</option>
                      </select>
                  </fieldset>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <input
                type="reset"
                class="btn bg-light-secondary"
                data-dismiss="modal"
                value="Close"
              />
              <input
                type="submit"
                class="btn btn-primary"
                value="Add Order Delivery"
              />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/warehouse/delivery_list.html
{% load static %}

<div class="row">
  <div class="col-12">
    <div class="content-header">Delivery List</div>
  </div>
</div>

<!-- Wizard Starts -->
<section id="multiple-select2">
  <div class="row">
    <div class="col-xl-12 col-lg-12">
      <div class="card">
        <div class="card-header">
          <div class="float-right">
            <div class="row mb-1">
              <!-- Create delivery Start -->
              <button
                type="button"
                class="btn bg-light-primary ml-1"
                data-toggle="modal"
                data-target="#create_delivery"
              >
                <i class="fa ft-plus-circle mr-1"></i>Create Delivery
              </button>
              <!-- Create delivery End-->
              {% include "warehouse/create_delivery.html" %}
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="card-content">
            <div class="table-responsive">
              <table
                class="table table-striped table-bordered zero-configuration"
              >
                <thead>
                  <tr>
                    <th>Order ID</th>
                    <th>Customer Name</th>
                    <th>Delivery Location</th>
                    <th>Status</th>
                    <th>Order Date</th>
                    <th>Expected Delivery Date</th>
                    <th>Delivery Date</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  
                  <tr>
                    <td>James Peter</td>
                    <td>jamespeter@laurel.com</td>
                    <td>East village</td>

                    <td>
                      <span class="badge bg-light-warning">On Packing</span>
                    </td>
                    <td>Jul 8, 2024</td>
                    <td>-</td>
                    <td>-</td>
                    <td>
                      <a
                        data-toggle="modal"
                        data-target="#update_delivery"
                        href="javascript:;"
                        class="success p-0"
                      >
                        <i class="ft-edit font-medium-3 mr-2"></i>
                      </a>
                      <a href="javascript:;" class="danger p-0">
                        <i class="ft-trash-2 font-medium-3"></i>
                      </a>
                    </td>
                    
                  </tr>

                  <tr>
                    <td>James Peter</td>
                    <td>jamespeter@laurel.com</td>
                    <td>East village</td>

                    <td>
                      <span class="badge bg-light-primary">In Transit</span>
                    </td>
                    <td>Jul 4, 2024</td>
                    <td>Jul 6, 2024</td>
                    <td>-</td>
                    <td>
                      <a
                        data-toggle="modal"
                        data-target="#update_delivery"
                        href="javascript:;"
                        class="success p-0"
                      >
                        <i class="ft-edit font-medium-3 mr-2"></i>
                      </a>
                      <a href="javascript:;" class="danger p-0">
                        <i class="ft-trash-2 font-medium-3"></i>
                      </a>
                    </td>
                  </tr>

                  <tr>
                    <td>James Peter</td>
                    <td>jamespeter@laurel.com</td>
                    <td>East village</td>

                    <td>
                      <span class="badge bg-light-success">Delivered</span>
                    </td>
                    <td>Jul 2, 2024</td>
                    <td>Jul 4, 2024</td>
                    <td>Jul 4, 2024</td>
                    <td>
                      <a
                        data-toggle="modal"
                        data-target="#update_delivery"
                        href="javascript:;"
                        class="success p-0"
                      >
                        <i class="ft-edit font-medium-3 mr-2"></i>
                      </a>
                      <a href="javascript:;" class="danger p-0">
                        <i class="ft-trash-2 font-medium-3"></i>
                      </a>
                    </td>
                  </tr>

                  <tr>
                    <td>James Peter</td>
                    <td>jamespeter@laurel.com</td>
                    <td>East village</td>

                    <td>
                      <span class="badge bg-light-success">Delivered</span>
                    </td>
                    <td>Jun 24, 2024</td>
                    <td>Jun 26, 2024</td>
                    <td>Jun 26, 2024</td>
                    <td>
                      <a
                        data-toggle="modal"
                        data-target="#update_delivery"
                        href="javascript:;"
                        class="success p-0"
                      >
                        <i class="ft-edit font-medium-3 mr-2"></i>
                      </a>
                      <a href="javascript:;" class="danger p-0">
                        <i class="ft-trash-2 font-medium-3"></i>
                      </a>
                    </td>
                  </tr>

                  <tr>
                    <td>James Peter</td>
                    <td>jamespeter@laurel.com</td>
                    <td>East village</td>

                    <td>
                      <span class="badge bg-light-success">Delivered</span>
                    </td>
                    <td>Jun 12, 2024</td>
                    <td>Jun 14, 2024</td>
                    <td>Jun 13, 2024</td>
                    <td>
                      <a
                        data-toggle="modal"
                        data-target="#update_delivery"
                        href="javascript:;"
                        class="success p-0"
                      >
                        <i class="ft-edit font-medium-3 mr-2"></i>
                      </a>
                      <a href="javascript:;" class="danger p-0">
                        <i class="ft-trash-2 font-medium-3"></i>
                      </a>

                    </td>
                  </tr>

                  {% include "warehouse/update_delivery.html" %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'vendors/js/vendors.min.js' %}"></script>
    <script src="{% static 'vendors/js/switchery.min.js' %}"></script>
    <script src="{% static 'vendors/js/vendors.min.js' %}"></script>
    <script src="{% static 'vendors/js/switchery.min.js' %}"></script>
    <script src="{% static 'vendors/js/select2.full.min.js' %}"></script>
    <script src="{% static 'app/js/select2.min.js' %}"></script>
    <!-- BEGIN PAGE LEVEL JS-->
    <!-- <script src="{% static 'app/js/data-tables/dt-data-sources.min.js' %}"></script> -->
    <!-- END PAGE LEVEL JS-->

    <script src="{% static 'app/js/ex-component-upload.min.js' %}"></script>
  </div>
</section>

src/templates/warehouse/file_upload.html
<div class="form-group">
  <div class="row">
    <div class="col-12">
      <label for="file-upload" class="btn btn-secondary mt-3">
        <input id="file-upload" type="file" style="display: none" /> Attach
        Documents
      </label>
    </div>
    <div class="col-12">
      <textarea
        rows="5"
        class="form-control square"
        placeholder="Add a comment  "
        name="comment3"
      ></textarea>
    </div>
  </div>
</div>

src/templates/warehouse/sidebar.html
{% load static %}

<div
  class="app-sidebar menu-fixed"
  data-background-color="white"
  data-image="../app-assets/img/sidebar-bg/01.jpg"
  data-scroll-to-active="true"
>
  <!-- main menu header-->
  <!-- Sidebar Header starts-->
  <div class="sidebar-header">
    <div class="logo clearfix">
      <a class="logo-text mx-0">
        <div class="logo-img">
          <img
            style="height: 45px"
            src="{% static 'app/img/logos/logo.png' %}"
            alt="Laurel - AG & Water"
          />
        </div>
        <span class="text">Laurel</span>
      </a>
      <a
        class="nav-toggle d-none d-lg-none d-xl-block font-large-1 text-secondary pl-5"
        id="sidebarToggle"
        href="javascript:;"
      >
        <i
          class="toggle-icon ft-arrow-right-circle bg-white rounded-circle"
          data-toggle="expanded"
        ></i>
      </a>
      <a
        class="nav-close d-block d-lg-block d-xl-none"
        id="sidebarClose"
        href="javascript:;"
      >
        <i class="ft-x"></i>
      </a>
    </div>
  </div>
  <!-- Sidebar Header Ends-->
  <!-- / main menu header-->
  <!-- main menu content-->
  <div class="sidebar-content main-menu-content">
    <div class="nav-container">
      <ul
        class="navigation navigation-main"
        id="main-menu-navigation"
        data-menu="menu-navigation"
      >
        <li
          class="nav-item {% if 'dashboard' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:dashboard' %}"
            ><i class="ft-home"></i
            ><span class="menu-title" data-i18n="Dashboard">Dashboard</span></a
          >
        </li>
        <li
          class="nav-item {% if 'warehouse_list' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:warehouse_list' %}"
            ><i class="ft-archive"></i
            ><span class="menu-title" data-i18n="Dashboard">Warehouse</span></a
          >
        </li>
        <li
          class="nav-item {% if 'customer' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:customer_list' %}"
            ><i class="ft-users"></i
            ><span class="menu-title" data-i18n="Dashboard">Customers</span></a
          >
        </li>
        <li
          class="nav-item {% if 'warehouse_products' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:warehouse_products' %}"
            ><i class="ft-list"></i
            ><span class="menu-title" data-i18n="Dashboard">Products</span></a
          >
        </li>
        <li
          class="nav-item {% if 'user_list' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:user_list' %}"
            ><i class="ft-user"></i
            ><span class="menu-title" data-i18n="Dashboard">Users</span></a
          >
        </li>
        <li
          class="nav-item {% if 'recurring_order' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:recurring_order' %}"
            ><i class="ft-rotate-cw"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Recurring Orders</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'order_list' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:order_list' %}"
            ><i class="ft-shopping-bag"></i
            ><span class="menu-title" data-i18n="Dashboard">Orders</span></a
          >
        </li>
        <li
          class="nav-item {% if 'express_delivery' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:express_delivery' %}"
            ><i class="ft-truck"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Express Delivery</span
            ></a
          >
        </li>
      </ul>
    </div>
  </div>
  <!-- main menu content-->
  <div class="sidebar-background"></div>
  <!-- main menu footer-->
  <!-- include includes/menu-footer-->
  <!-- main menu footer-->
  <!-- / main menu-->
</div>

src/templates/warehouse/time_line.html
<div class="card-header">
  <div class="float-right">
    <div
      class="modal fade text-left"
      id="TimeLine"
      tabindex="-1"
      role="dialog"
      aria-labelledby="myModalLabel33"
      aria-hidden="true"
      data-backdrop="false"
    >
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">PROJ016968 Order History</h4>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true"
                ><i class="ft-x font-medium-2 text-bold-700"></i
              ></span>
            </button>
          </div>
          <form action="#">
            <div class="modal-body">
              <!--Vertical Timeline Starts-->
              <section
                id="vertical-timeline-center"
                class="timeline-center timeline-wrapper col-sm-10 col-12 offset-sm-1"
              >
                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>

                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer">Pre-Processing</span>
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3">5th May, 2024</span>
                        </div>
                      </div>
                      <div class="card-content"></div>
                    </div>
                  </li>
                </ul>

                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <span></span>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>
                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer"
                            >In Transit-Outbound</span
                          >
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3">7th May, 2024</span>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>

                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>

                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer">Customer Delivery</span>
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3">15 May, 2024</span>
                        </div>
                      </div>
                      <div class="card-content"></div>
                    </div>
                  </li>
                </ul>

                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <span></span>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>
                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer"
                            >Final Pick-up and Inspection</span
                          >
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3"
                            >18 June, 2016 at 4.50 P.M</span
                          >
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>

                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>

                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer"
                            >In Transit - Inbound</span
                          >
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3"
                            >20 June, 2016 at 4.50 P.M</span
                          >
                        </div>
                      </div>
                      <div class="card-content"></div>
                    </div>
                  </li>
                </ul>

                <ul class="timeline">
                  <li class="timeline-line"></li>
                  <span></span>
                  <li class="timeline-item">
                    <div class="timeline-badge">
                      <span
                        class="bg-primary bg-lighten-4"
                        data-toggle="tooltip"
                        data-placement="left"
                        title="Nullam facilisis fermentum"
                      >
                        <i class="ft-command primary"></i>
                      </span>
                    </div>
                    <div class="timeline-card card shadow-z-1">
                      <div class="card-header pt-0">
                        <h4 class="mb-0 card-title">
                          <span class="cursor-pointer">Warehouse Storage</span>
                        </h4>
                        <div class="card-subtitle text-muted mt-0">
                          <span class="font-small-3">28 June, 2024</span>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              </section>
              <!--Vertical Timeline Ends-->
            </div>
            <div class="modal-footer">
              <input
                type="reset"
                class="btn bg-light-secondary"
                data-dismiss="modal"
                value="Close"
              />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/warehouse/warehouse_wrapper.html
{% extends "base.html" %}
{% block page_content %}
{% include 'warehouse/sidebar.html'%}
<div class="main-panel">
  <!-- BEGIN : Main Content-->
  <div class="main-content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        {% include template_name %}
      <!-- Wizard Ends -->
    </div>
  </div>
  <!-- END : End Main Content-->
  <!-- BEGIN : Footer-->
  {% include "footer.html" %}
  <!-- End : Footer--><!-- Scroll to top button -->
  <button class="btn btn-primary scroll-top" type="button">
    <i class="ft-arrow-up"></i>
  </button>
</div>
{% endblock page_content%}