src/apps/proposal/urls.py
from django.urls import path
from . import views

app_name = "proposal"


warehouse_urls = [
    path("warehouse_list", views.WarehouseList.as_view(), name="warehouse_list"),
    path("warehouse_products", views.WarehouseProducts.as_view(), name="warehouse_products"),
    path("user_list", views.UserList.as_view(), name="user_list"),
    path("order_list", views.OrderList.as_view(), name="order_list"),
    path("recurring_order", views.RecurringOrder.as_view(), name="recurring_order"),
    path("order", views.Order.as_view(), name="order"),
    path("return_order", views.ReturnOrder.as_view(), name="return_order"),
    path("express_delivery", views.ExpressDelivery.as_view(), name="express_delivery"),
    path("delivery_list", views.Delivery.as_view(), name="delivery_list"),
]

urlpatterns = [
    #     path("", views.LoginView.as_view(), name="login"),

    path("dashboard", views.Dashboard.as_view(), name="dashboard"),
    path("proposal-list", views.ProposalList.as_view(), name="proposal_list"),
    path("proposal-preview", views.ProposalPreview.as_view(),
         name="proposal_preview"),
    path("opportunity-list", views.OpportunityList.as_view(),
         name="opportunity_list"),
    path("opportunity-details", views.OpportunityDetails.as_view(),
         name="opportunity_details"),
    path("home", views.Home.as_view(), name="home"),
    path("opportunity", views.Opportunity.as_view(), name="opportunity"),
    path("generate_estimate_table", views.GenerateEstimateTable.as_view(),
         name="generate_estimate_table"),
    path("material-list", views.MaterialListView.as_view(), name="material_list"),
    path("glue-material-list", views.GlueListView.as_view(),
         name="glue_material_list"),
    path("final-ready-material-list", views.FinalReadyMaterialListView.as_view(),
         name="final_ready_material_list"),
    path("estimate", views.EstimateView.as_view(), name="estimate"),
    path("proposal", views.ProposalView.as_view(), name="proposal"),
    path("proposal-creation", views.ProposalCreateView.as_view(),
         name="proposal-creation"),
    path("products", views.ProductList.as_view(), name="product_list"),
    path("labor-cost", views.LaborCostList.as_view(), name="labor_cost_list"),
    path("customer", views.CustomerList.as_view(), name="customer_list"),
    path("task", views.TaskList.as_view(), name="task_list"),
    path("vendor", views.VendorList.as_view(), name="vendor_list"),
    path("inbox", views.InboxList.as_view(), name="inbox_list"),
    path("update_profile", views.UpdateProfile.as_view(), name="update_profile"),
    path("motor_fla_calculator", views.MotorFLACalculator.as_view(),
         name="motor_fla_calculator"),
    path("pump_flo_calculator", views.PumpFLOCalculator.as_view(), name="pump_flo_calculator"),
    path("netafim_calculator", views.NetafimCalculator.as_view(), name="netafim_calculator"),
    path("overlap_pro_calculator", views.OverlapProCalculator.as_view(),
         name="overlap_pro_calculator"),
    path("southwire_calculator", views.SouthwireCalculator.as_view(),
         name="southwire_calculator"),
    path("paigewire_calculator", views.PaigewireCalculator.as_view(),
         name="paigewire_calculator"),
    path("choose_screens", views.ChooseScreens.as_view(), name="choose_screens"),
    path("coming_soon", views.ComingSoon.as_view(), name="coming_soon"),
]+warehouse_urls

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.proposal.urls", 'proposal'), namespace="proposal")),
    path("", include(("apps.user.urls", 'user'), namespace="user")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/v1/", include("core.api_router")),
]

src/apps/proposal/models.py
from django.db import models

# Create your models here.

src/apps/proposal/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


################################################
################ Base View START ###############
################################################

class LoginBaseMixin(LoginRequiredMixin):
    """
    Base mixin for requiring login before accessing views.
    """
    ...


class ProposalViewMixin(LoginBaseMixin, TemplateView):
    """
    Mixin for rendering proposal-related views.
    """
    template_name = "proposal/proposal_wrapper.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["template_name"] = self.render_template_name
        return context


class WarehouseViewMixin(LoginBaseMixin, TemplateView):
    """
    Mixin for rendering warehouse-related views.
    """
    template_name = "warehouse/warehouse_wrapper.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["template_name"] = self.render_template_name
        return context


################################################
################# Base View END ################
################################################


class Home(LoginBaseMixin, TemplateView):
    template_name = "proposal/index.html"


class InboxList(LoginBaseMixin, TemplateView):
    template_name = "proposal/inbox_list.html"


class UpdateProfile(LoginBaseMixin, TemplateView):
    template_name = "proposal/update_profile.html"


class MotorFLACalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/motor_fla_calculator.html"


class PumpFLOCalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/pump_flo_calculator.html"


class NetafimCalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/netafim_calculator.html"


class OverlapProCalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/overlap_pro_calculator.html"


class SouthwireCalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/southwire_calculator.html"


class PaigewireCalculator(LoginBaseMixin, TemplateView):
    template_name = "proposal/paigewire_calculator.html"


class ChooseScreens(LoginBaseMixin, TemplateView):
    template_name = "proposal/choose_screens.html"


class ComingSoon(LoginBaseMixin, TemplateView):
    template_name = "proposal/coming_soon.html"


################################################
############ Opportunity View START ############
################################################


class Opportunity(ProposalViewMixin):
    """
    View class for rendering the list of opportunity.
    """
    render_template_name = "proposal/opportunity.html"


class ProposalList(ProposalViewMixin):
    """
    View class for rendering the list of proposal.
    """
    render_template_name = "proposal/proposal_list.html"


class ProposalPreview(ProposalViewMixin):
    """
    View class for rendering the proposal preview.
    """
    render_template_name = "proposal/proposal_preview.html"


class OpportunityList(ProposalViewMixin):
    """
    View class for rendering the list of opportunity.
    """
    render_template_name = "proposal/opportunity_list.html"


class OpportunityDetails(ProposalViewMixin):
    """
    View class for rendering the opportunity details.
    """
    render_template_name = "proposal/opportunity_details.html"


class GenerateEstimateTable(ProposalViewMixin):
    """
    View class for rendering the estimate generation.
    """
    render_template_name = "proposal/generate_estimate_table.html"


class MaterialListView(ProposalViewMixin):
    """
    View class for rendering the list of materials.
    """
    render_template_name = "proposal/step_2.html"


class GlueListView(ProposalViewMixin):
    """
    View class for rendering the list of glue.
    """
    render_template_name = "proposal/step_3.html"


class FinalReadyMaterialListView(ProposalViewMixin):
    """
    View class for rendering the list of final ready materials.
    """
    render_template_name = "proposal/step_4.html"


class EstimateView(ProposalViewMixin):
    """
    View class for rendering the estimations.
    """
    render_template_name = "proposal/step_5.html"


class ProposalView(ProposalViewMixin):
    """
    View class for rendering the proposals.
    """
    render_template_name = "proposal/step_6.html"


class ProposalCreateView(ProposalViewMixin):
    """
    View class for rendering the proposal creation.
    """
    render_template_name = "proposal/proposel_creation.html"


class ProductList(ProposalViewMixin):
    """
    View class for rendering the list of proposal product.
    """
    render_template_name = "proposal/product_list.html"


class LaborCostList(ProposalViewMixin):
    """
    View class for rendering the list of proposal labor.
    """
    render_template_name = "proposal/labor_cost_list.html"


class CustomerList(ProposalViewMixin):
    """
    View class for rendering the list of proposal customer.
    """
    render_template_name = "proposal/customer_list.html"


class TaskList(ProposalViewMixin):
    """
    View class for rendering the list of proposal task.
    """
    render_template_name = "proposal/task_list.html"


class VendorList(ProposalViewMixin):
    """
    View class for rendering the list of proposal vendor.
    """
    render_template_name = "proposal/vendor_list.html"


################################################
############ Opportunity View End ##############
################################################


##############################################
############ Warehouse View START ############
##############################################


class Dashboard(WarehouseViewMixin):
    render_template_name = "warehouse/dashboard.html"


class WarehouseProducts(WarehouseViewMixin):
    """
    View class for rendering the list of warehouse products.
    """
    render_template_name = "warehouse/warehouse_product_list.html"


class WarehouseList(WarehouseViewMixin):
    """
    View class for rendering the list of warehouses.
    """
    render_template_name = "warehouse/warehouse_list.html"


class UserList(WarehouseViewMixin):
    """
    View class for rendering the list of users.
    """
    render_template_name = "warehouse/user_list.html"


class OrderList(WarehouseViewMixin):
    """
    View class for rendering the list of orders.
    """
    render_template_name = "warehouse/order_list.html"


class RecurringOrder(WarehouseViewMixin):
    """
    View class for rendering recurring order details.
    """
    render_template_name = "warehouse/recurring_order.html"


class Order(WarehouseViewMixin):
    """
    View class for rendering a single order.
    """
    render_template_name = "warehouse/orders/order.html"


class ReturnOrder(WarehouseViewMixin):
    """
    View class for rendering a single return order.
    """
    render_template_name = "warehouse/orders/return_order.html"


class ExpressDelivery(WarehouseViewMixin):
    """
    View class for rendering express delivery details.
    """
    render_template_name = "warehouse/express_delivery.html"


class Delivery(WarehouseViewMixin):
    """
    View class for rendering list of delivery details.
    """
    render_template_name = "warehouse/delivery_list.html"

src/templates/proposal/based_on_products.html
<div class="form-group">
  <div id="invoice-template" class="card-body pb-0">
    <div class="row">
      <div class="col-md-6 col-12 text-left">
        <p>
          <span class="text-muted">Date :</span>
          May 13, 2024
        </p>
        <p>
          <span class="text-muted">Job #</span>
          Existi
        </p>
        <p>
          <span class="text-muted">Job Name:</span> Existing Pump Relocation And
          New 10" Discharge
        </p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table zero-configuration">
            <thead>
              <tr>
                <th>Product Number</th>
                <th>Product Name</th>
                <th class="text-right">Product Price</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>
                  <span class="font-weight-bold">401020</span>
                </th>
                <td>
                  <span>ELBOW S 40 X 90</span>
                  <div>
                    <textarea
                      style="width: 85%"
                      rows="4"
                      placeholder="Product Description"
                    ></textarea>
                  </div>
                </td>
                <td class="text-right">
                  <span>$145.32</span>
                </td>
              </tr>
              <tr>
                <th>
                  <span class="font-weight-bold">2800-117500</span>
                </th>
                <td>
                  <span>Ball Valve Riser 3/4 FHTxMHT</span>
                  <div>
                    <textarea
                      style="width: 85%"
                      rows="4"
                      placeholder="Product Description"
                    ></textarea>
                  </div>
                </td>
                <td class="text-right">
                  <span>$742.02</span>
                </td>
              </tr>
              <tr>
                <th>
                  <span class="font-weight-bold">SINGLE-C</span>
                </th>
                <td>
                  <span>Trench: Chain - One pipe in trench</span>
                  <div>
                    <textarea
                      style="width: 85%"
                      rows="4"
                      placeholder="Product Description"
                    ></textarea>
                  </div>
                </td>
                <td class="text-right">
                  <span>$471.07</span>
                </td>
              </tr>
              <tr>
                <td scope="row">FRT</td>
                <td>
                  <p>FRT : Frieght</p>
                </td>
                <td class="text-right">$250.00</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <th class="text-right">
                  <p>TOTAL ESTIMATE - ITEMS LISTED :</p>
                </th>
                <th class="text-right">$1608.41</th>
              </tr>
            </tbody>
          </table>
        </div>
        <br />
      </div>
    </div>
  </div>
</div>

src/templates/proposal/calculator_sidebar.html
{% load static %}
<div
  class="app-sidebar menu-fixed"
  data-background-color="white"
  data-image="../app-assets/img/sidebar-bg/01.jpg"
  data-scroll-to-active="true"
>
  <!-- main menu header-->
  <!-- Sidebar Header starts-->
  <div class="sidebar-header">
    <div class="logo clearfix">
      <a class="logo-text mx-0">
        <div class="logo-img">
          <img
            style="height: 45px"
            src="{% static 'app/img/logos/logo.png' %}"
            alt="Laurel - AG & Water"
          />
        </div>
        <span class="text">Laurel</span>
      </a>
      <a
        class="nav-toggle d-none d-lg-none d-xl-block font-large-1 text-secondary pl-5"
        id="sidebarToggle"
        href="javascript:;"
      >
        <i
          class="toggle-icon ft-arrow-right-circle bg-white rounded-circle"
          data-toggle="expanded"
        ></i>
      </a>
      <a
        class="nav-close d-block d-lg-block d-xl-none"
        id="sidebarClose"
        href="javascript:;"
      >
        <i class="ft-x"></i>
      </a>
    </div>
  </div>
  <!-- Sidebar Header Ends-->
  <!-- / main menu header-->
  <!-- main menu content-->
  <div class="sidebar-content main-menu-content">
    <div class="nav-container">
      <ul
        class="navigation navigation-main"
        id="main-menu-navigation"
        data-menu="menu-navigation"
      >
        <li
          class="nav-item {% if 'motor_fla_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:motor_fla_calculator' %}"
            ><i class="ft-bar-chart-2"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Motor FLA Calculator</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'pump_flo_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:pump_flo_calculator' %}"
            ><i class="ft-box"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Pump FLO Calculator</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'netafim_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:netafim_calculator' %}"
            ><i class="ft-compass"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Netafim Calculator</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'overlap_pro_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:overlap_pro_calculator' %}"
            ><i class="ft-layout"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Overlap Pro Calculator</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'southwire_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:southwire_calculator' %}"
            ><i class="ft-loader"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Southwire Calculator</span
            ></a
          >
        </li>
        <li
          class="nav-item {% if 'paigewire_calculator' in request.path %}active{% endif %}"
        >
          <a href="{% url 'proposal:paigewire_calculator' %}"
            ><i class="ft-sunrise"></i
            ><span class="menu-title" data-i18n="Dashboard"
              >Paigewire Calculator</span
            ></a
          >
        </li>
      </ul>
    </div>
  </div>
  <!-- main menu content-->
  <div class="sidebar-background"></div>
  <!-- main menu footer-->
  <!-- include includes/menu-footer-->
  <!-- main menu footer-->
  <!-- / main menu-->
</div>

src/templates/proposal/netafim_calculator.html
{% extends "app/calculator_base.html" %} {% load static %} {% block page_content %}

<div class="row">
  <div class="col-12">
    <div class="content-header">Netafim Calculator</div>
  </div>
</div>

<!-- Wizard Starts -->
<section id="icon-tabs">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content">
          <div class="card-body">
            <iframe
              src="https://www.netafim.com/en/products-and-solutions/tools/hydrocalc-3.0"
              width="100%"
              height="700px"
            ></iframe>
          </div>
        </div>
      </div>
    </div>

    <!-- BEGIN PAGE LEVEL JS-->
    <!-- <script src="{% static 'app/js/data-tables/dt-data-sources.min.js' %}"></script> -->
    <!-- END PAGE LEVEL JS-->
  </div>
</section>
{% endblock page_content%}

src/templates/proposal/step_2.html
{% extends "base.html" %} {% load static %} {% block page_content %}

<div class="row">
  <div class="col-12">
    <div class="content-header">Material List Directly from Irricad</div>
  </div>
</div>

<!-- Wizard Starts -->
<section id="configuration">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"></h4>
        </div>
        <div class="card-content">
          <div class="card-body">
            <p></p>
            <div class="table-responsive">
              <table
                class="table table-striped table-bordered zero-configuration"
              >
                <thead>
                  <tr>
                    <th>Quantity</th>
                    <th>Description</th>
                    <th>Item Number</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>3</td>
                    <td>TEE S40 2"</td>
                    <td>401020</td>
                  </tr>
                  <tr>
                    <td>15</td>
                    <td>ELBOW S40 2" X 90</td>
                    <td>406020</td>
                  </tr>
                  <tr>
                    <td>6</td>
                    <td>ELBOW S40 2" X 45</td>
                    <td>417020</td>
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>CAP S40 2"</td>
                    <td>447020</td>
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>FLUSHOUT DRIP ABOVE 2"</td>
                    <td>1100-001000</td>
                  </tr>
                  <tr>
                    <td>64</td>
                    <td>PERMA-LOC X SWIVEL-W TEE 062</td>
                    <td>2800-006000</td>
                  </tr>
                  <tr>
                    <td>63</td>
                    <td>SADDLE 1/2" X 2"</td>
                    <td>2800-105000</td>
                  </tr>
                  <tr>
                    <td>64</td>
                    <td>MALE HOSE ADAP X 1/2"S(3/4"SP)</td>
                    <td>2800-114000</td>
                  </tr>
                  <tr>
                    <td>64</td>
                    <td>Ball Valve Riser 3/4" FHTxMHT</td>
                    <td>2800-117500</td>
                  </tr>
                  <tr>
                    <td>128</td>
                    <td>FIGURE 8 062</td>
                    <td>2800-118500</td>
                  </tr>
                  <tr>
                    <td>24000</td>
                    <td>UNIRAM .62/45 E.5336 COIL</td>
                    <td>4400-458500</td>
                  </tr>
                  <tr>
                    <td>2000</td>
                    <td>PIPE PVC IPS CL125 2" SW</td>
                    <td>5400-007500</td>
                  </tr>
                  <tr>
                    <td>20</td>
                    <td>PIPE PVC IPS S40 2" SW</td>
                    <td>5400-027000</td>
                  </tr>
                  <tr>
                    <td>64</td>
                    <td>FLEX RISER 1/2" X 48"</td>
                    <td>6200-008000</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>NELSON VLV 2" GR 18-80 PR</td>
                    <td>6350-001550</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>VENT-1"CAV X 2"COUP</td>
                    <td>ASSM-0625</td>
                  </tr>
                  <tr>
                    <td>7675</td>
                    <td>DRIP IN-Netafim UniRam Inline 0.5gph PC</td>
                    <td>NURAM0.5</td>
                  </tr>
                  <tr>
                    <td>7675</td>
                    <td>Netafim Ram 0.5 gph</td>
                    <td>RAM0.5</td>
                  </tr>
                  <tr>
                    <td>1485</td>
                    <td>Trench: Chain - One pipe in trench</td>
                    <td>SINGLE-C</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br />
            <div class="row">
              <div class="col-12">
                <div class="float-right">
                  <a
                    href="{% url 'proposal:material_list' %}"
                    role="menuitem"
                    class="btn btn-primary btn-secondary"
                    >Previous</a
                  >
                  <a
                    href="{% url 'proposal:glue_material_list' %}"
                    role="menuitem"
                    class="btn btn-primary"
                    >Next</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="{% static 'app/js/ex-component-upload.min.js' %}"></script>

{% endblock page_content%}

src/templates/proposal/step_3.html
{% extends "base.html" %} {% load static %} {% block page_content %}

<div class="row">
  <div class="col-12">
    <div class="content-header">Glue and Additional Material</div>
  </div>
</div>

<!-- Wizard Starts -->
<section id="configuration">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"></h4>
        </div>
        <div class="card-content">
          <div class="card-body">
            <p></p>
            <div class="table-responsive">
              <table
                class="table table-striped table-bordered zero-configuration"
              >
                <thead>
                  <tr>
                    <th>Quantity</th>
                    <th>Description</th>
                    <th>Item Number</th>
                    <th>Category</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1</td>
                    <td>Cement -711 Heavy Gray, Gallon</td>
                    <td>4200-001600</td>
                    <td>#N/A</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>Cement -719 Extra Heavy Gray, Quart</td>
                    <td>4200-002500</td>
                    <td>GLU010</td>
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>Cement - Primer Purple P70 Gal</td>
                    <td>4200-007500</td>
                    <td>GLU020</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>CEMENT - RED HOT CLEAR, PINT</td>
                    <td>4200-005000</td>
                    <td>GLU010</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>CEMENT - RED HOT CLEAR, PINT (HOSE FITTINGS)</td>
                    <td>4200-005000</td>
                    <td>FHO</td>
                  </tr>
                  <tr>
                    <td>7</td>
                    <td>Cement - Empty Can, Quart 1.75" Neck</td>
                    <td>4200-013000</td>
                    <td>GLU040</td>
                  </tr>
                  <tr>
                    <td>7</td>
                    <td>Cement - Empty Can, Pint 1.75" Neck</td>
                    <td>4200-013500</td>
                    <td>GLU040</td>
                  </tr>
                  <tr>
                    <td>14</td>
                    <td>Cement - Dauber for Quart Can</td>
                    <td>4200-014500</td>
                    <td>GLU040</td>
                  </tr>
                  <tr>
                    <td>4</td>
                    <td>Cement - Dauber for Pint Can</td>
                    <td>4200-015000</td>
                    <td>GLU040</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>Cement - Dauber for Pint Can (HOSE FITTINGS)</td>
                    <td>4200-015000</td>
                    <td>FHO</td>
                  </tr>
                  <tr>
                    <td>25</td>
                    <td>COUPLER BLACK 1/2"</td>
                    <td>2800-116500</td>
                    <td>FHO910</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>COUPLER S40 2"</td>
                    <td>429020</td>
                    <td>FMP429</td>
                  </tr>
                  <tr>
                    <td>11</td>
                    <td>PERMA-LOC X SWIVEL-W TEE 062</td>
                    <td>2800-006000</td>
                    <td>FHO010</td>
                  </tr>
                  <tr>
                    <td>25</td>
                    <td>PERMA-LOC COUPLING 062</td>
                    <td>2800-001000</td>
                    <td>FHO005</td>
                  </tr>
                  <tr>
                    <td>11</td>
                    <td>Ball Valve, Riser 3/4" FHTxMHT</td>
                    <td>2800-117500</td>
                    <td>FHO915</td>
                  </tr>
                  <tr>
                    <td>11</td>
                    <td>MALE HOSE ADAP X 1/2"S(3/4"SP)</td>
                    <td>2800-114000</td>
                    <td>FHO905</td>
                  </tr>
                  <tr>
                    <td>22</td>
                    <td>FIGURE 8 062</td>
                    <td>2800-118500</td>
                    <td>FHO920</td>
                  </tr>
                  <tr>
                    <td>36</td>
                    <td>FLEX RISER 1/2" X 48"</td>
                    <td>6200-008000</td>
                    <td>TUB030</td>
                  </tr>
                  <tr>
                    <td>12</td>
                    <td>SADDLE 1/2" X 2"</td>
                    <td>2800-105000</td>
                    <td>FHO900</td>
                  </tr>
                  <tr>
                    <td>3</td>
                    <td>CUT PIPE PVC S40 2" x 48"</td>
                    <td>5400-031120</td>
                    <td>PIP010</td>
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>SURVEY FLAGS GLO ORA 21" WIRE</td>
                    <td>3600-004500</td>
                    <td>FSO020</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br />
            <div class="row">
              <div class="col-12">
                <div class="float-right">
                  <a
                    href="{% url 'proposal:material_list' %}"
                    role="menuitem"
                    class="btn btn-primary btn-secondary"
                    >Previous</a
                  >
                  <a
                    href="{% url 'proposal:final_ready_material_list' %}"
                    role="menuitem"
                    class="btn btn-primary"
                    >Next</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="{% static 'app/js/ex-component-upload.min.js' %}"></script>

{% endblock page_content%}