src/apps/proposal/urls.py
from django.urls import path
from . import views

app_name = "proposal"


warehouse_urls = [
    path("warehouse_list", views.WarehouseList.as_view(), name="warehouse_list"),
    path("warehouse_products", views.WarehouseProducts.as_view(), name="warehouse_products"),
    path("user_list", views.UserList.as_view(), name="user_list"),
    path("order_list", views.OrderList.as_view(), name="order_list"),
    path("recurring_order", views.RecurringOrder.as_view(), name="recurring_order"),
    path("order", views.Order.as_view(), name="order"),
    path("return_order", views.ReturnOrder.as_view(), name="return_order"),
    path("express_delivery", views.ExpressDelivery.as_view(), name="express_delivery"),
    path("delivery_list", views.Delivery.as_view(), name="delivery_list"),
]

urlpatterns = [
    #     path("", views.LoginView.as_view(), name="login"),

    path("dashboard", views.Dashboard.as_view(), name="dashboard"),
    path("proposal-list", views.ProposalList.as_view(), name="proposal_list"),
    path("proposal-preview", views.ProposalPreview.as_view(),
         name="proposal_preview"),
    path("opportunity-list", views.OpportunityList.as_view(),
         name="opportunity_list"),
    path("opportunity-details", views.OpportunityDetails.as_view(),
         name="opportunity_details"),
    path("home", views.Home.as_view(), name="home"),
    path("opportunity", views.Opportunity.as_view(), name="opportunity"),
    path("generate_estimate_table", views.GenerateEstimateTable.as_view(),
         name="generate_estimate_table"),
    path("material-list", views.MaterialListView.as_view(), name="material_list"),
    path("glue-material-list", views.GlueListView.as_view(),
         name="glue_material_list"),
    path("final-ready-material-list", views.FinalReadyMaterialListView.as_view(),
         name="final_ready_material_list"),
    path("estimate", views.EstimateView.as_view(), name="estimate"),
    path("proposal", views.ProposalView.as_view(), name="proposal"),
    path("proposal-creation", views.ProposalCreateView.as_view(),
         name="proposal-creation"),
    path("products", views.ProductList.as_view(), name="product_list"),
    path("labor-cost", views.LaborCostList.as_view(), name="labor_cost_list"),
    path("customer", views.CustomerList.as_view(), name="customer_list"),
    path("task", views.TaskList.as_view(), name="task_list"),
    path("vendor", views.VendorList.as_view(), name="vendor_list"),
    path("inbox", views.InboxList.as_view(), name="inbox_list"),
    path("update_profile", views.UpdateProfile.as_view(), name="update_profile"),
    path("motor_fla_calculator", views.MotorFLACalculator.as_view(),
         name="motor_fla_calculator"),
    path("pump_flo_calculator", views.PumpFLOCalculator.as_view(), name="pump_flo_calculator"),
    path("netafim_calculator", views.NetafimCalculator.as_view(), name="netafim_calculator"),
    path("overlap_pro_calculator", views.OverlapProCalculator.as_view(),
         name="overlap_pro_calculator"),
    path("southwire_calculator", views.SouthwireCalculator.as_view(),
         name="southwire_calculator"),
    path("paigewire_calculator", views.PaigewireCalculator.as_view(),
         name="paigewire_calculator"),
    path("choose_screens", views.ChooseScreens.as_view(), name="choose_screens"),
    path("coming_soon", views.ComingSoon.as_view(), name="coming_soon"),
]+warehouse_urls

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.proposal.urls", 'proposal'), namespace="proposal")),
    path("", include(("apps.user.urls", 'user'), namespace="user")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/v1/", include("core.api_router")),
]

src/templates/warehouse/orders/customer_delivery.html
<div class="row">
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-primary">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-box font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">278</h3>
              <span>No of Products</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-danger">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-calendar font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">15/05/2024</h3>
              <span>Delivery Date</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-success">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-truck font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">Truck</h3>
              <span>Delivery Medium</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-warning">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-map-pin font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">Los Angeles</h3>
              <span>Location</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/warehouse/orders/final_pick_up_inspection.html
<div class="table-responsive">
  <table class="table table-striped table-bordered zero-configuration">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Inspection Status</th>
        <th>Product Quantity</th>
        <th>Ref No</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <!-- Row 1 -->
      <tr>
        <td>COMPANION FLG GALV 4" FLGXFPT</td>
        <td><span class="badge bg-light-danger">Failed</span></td>
        <td>12</td>
        <td>REF000206</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 2 -->
      <tr>
        <td>METAL FITTINGS</td>
        <td><span class="badge bg-light-success">Pass</span></td>
        <td>32</td>
        <td>REF001501</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 3 -->
      <tr>
        <td>td>SUPERNET PC 7.5GPH LR</td>
        <td><span class="badge bg-light-success">Pass</span></td>
        <td>48</td>
        <td>REF001805</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 4 -->
      <tr>
        <td>SN PRP SWVL LR ORG NZ W/30" ST</td>
        <td><span class="badge bg-light-warning">Pending</span></td>
        <td>14</td>
        <td>REF001307</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 5 -->
      <tr>
        <td>SN PC HEAD LT GRN LR W/DFLTR</td>
        <td><span class="badge bg-light-warning">Pending</span></td>
        <td>31</td>
        <td>REF000701</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 6 -->
      <tr>
        <td>SN HEAD 7.4GPH LT-GRN W/DFLT</td>
        <td><span class="badge bg-light-success">Pass</span></td>
        <td>5</td>
        <td>REF002806</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 7 -->
      <tr>
        <td>SN BL10.6GPH STK30" LD LRSS</td>
        <td><span class="badge bg-light-warning">Pending</span></td>
        <td>52</td>
        <td>REF000604</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 8 -->
      <tr>
        <td>SN PC HEAD 18.5GPH BLU W/DFLTR</td>
        <td><span class="badge bg-light-warning">Pending</span></td>
        <td>42</td>
        <td>REF001812</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 9 -->
      <tr>
        <td>VIBRONET BLU SPK 10.4GPH CV</td>
        <td><span class="badge bg-light-danger">Failed</span></td>
        <td>19</td>
        <td>REF002906</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 10 -->
      <tr>
        <td>MISTER BLU NOZZEL W/ CHECK VALVE NETAFIM VIBRONET</td>
        <td><span class="badge bg-light-success">Pass</span></td>
        <td>47</td>
        <td>REF002606</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
    </tbody>
  </table>
</div>

src/templates/warehouse/orders/in_transit_inbound.html
<div class="row">
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-primary">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-box font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">276</h3>
              <span>No of Products</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-danger">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-calendar font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">06/03/2023</h3>
              <span>Expected Return Date</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-success">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-truck font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">Truck</h3>
              <span>Delivery Medium</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-warning">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-map-pin font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">New York</h3>
              <span>Location</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/warehouse/orders/in_transit_outbound.html
<div class="row">
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-primary">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-box font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">278</h3>
              <span>No of Products</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-danger">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-calendar font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">15/05/2024</h3>
              <span>Expected Delivery Date</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-success">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-truck font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">Truck</h3>
              <span>Delivery Medium</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card card-inverse bg-warning">
      <div class="card-content">
        <div class="card-body">
          <div class="media">
            <div class="media-left align-self-center">
              <i class="ft-map-pin font-large-2 float-left"></i>
            </div>
            <div class="media-body text-right">
              <h3 class="card-text">Los Angeles</h3>
              <span>Location</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/warehouse/orders/order.html
{% load static %}

<div class="ml-3">
  <div class="row">
    <h5>
      Customer
    </h5>
    <span class="ml-1 border-right pr-2">
        Jane Smith
    </span>
    <h5 class="pl-2">
      Order Number
    </h5>
    <span class="ml-1 border-right pr-2">
        ORD-0000759
    </span>
    <h5 class="pl-2">
      Return Order Number
    </h5>
    <span class="ml-1 pr-3">
      <a href="{% url 'proposal:return_order' %}">R-ORD-0000759</a>
    </span>
  </div>
</div>

<!-- Wizard Starts -->
<section id="icon-tabs">
  <div class="row">
    <div class="col-12">
      <div class="card p-0 m-0">
        <div class="card-content">
          <div class="card-body py-0">
            <form class="icons-tab-steps">

              <h6>Pre-Processing</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./pre_processing.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>In Transit - Outbound</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./in_transit_outbound.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>Customer Delivery</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./customer_delivery.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              {% comment %} <h6>Final Pick-up and Inspection</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./final_pick_up_inspection.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>In Transit - Inbound</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./in_transit_inbound.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>Warehouse Storage</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./warehouse_storage.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset> {% endcomment %}
              
              <form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


<script src="{% static 'app/js/ex-component-upload.min.js' %}"></script>

src/templates/warehouse/orders/pre_processing.html
<div class="table-responsive">
  <table class="table table-striped table-bordered zero-configuration">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Status</th>
        <th>Product Quantity</th>
        <th>Ref No</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <!-- Row 1 -->
      <tr>
        <td>COMPANION FLG GALV 4" FLGXFPT</td>
        <td><span class="badge bg-light-primary">Packed</span></td>
        <td>12</td>
        <td>REF000206</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 2 -->
      <tr>
        <td>METAL FITTINGS</td>
        <td><span class="badge bg-light-success">Ready for Shipment</span></td>
        <td>32</td>
        <td>REF001501</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 3 -->
      <tr>
        <td>SUPERNET PC 7.5GPH LR</td>
        <td><span class="badge bg-light-success">Ready for Shipment</span></td>
        <td>48</td>
        <td>REF001805</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 4 -->
      <tr>
        <td>SN PRP SWVL LR ORG NZ W/30" ST</td>
        <td><span class="badge bg-light-danger">Unpacked</span></td>
        <td>14</td>
        <td>REF001307</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 5 -->
      <tr>
        <td>SN PC HEAD LT GRN LR W/DFLTR</td>
        <td><span class="badge bg-light-danger">Unpacked</span></td>
        <td>31</td>
        <td>REF000701</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 6 -->
      <tr>
        <td>SN HEAD 7.4GPH LT-GRN W/DFLT</td>
        <td><span class="badge bg-light-success">Ready for Shipment</span></td>
        <td>5</td>
        <td>REF002806</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 7 -->
      <tr>
        <td>SN BL10.6GPH STK30" LD LRSS</td>
        <td><span class="badge bg-light-danger">Unpacked</span></td>
        <td>52</td>
        <td>REF000604</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 8 -->
      <tr>
        <td>SN PC HEAD 18.5GPH BLU W/DFLTR</td>
        <td><span class="badge bg-light-danger">Unpacked</span></td>
        <td>42</td>
        <td>REF001812</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 9 -->
      <tr>
        <td>VIBRONET BLU SPK 10.4GPH CV</td>
        <td><span class="badge bg-light-primary">Packed</span></td>
        <td>19</td>
        <td>REF002906</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
      <!-- Row 10 -->
      <tr>
        <td>MISTER BLU NOZZEL W/ CHECK VALVE NETAFIM VIBRONET</td>
        <td><span class="badge bg-light-success">Ready for Shipment</span></td>
        <td>47</td>
        <td>REF002606</td>
        <td class="text-truncate">
          <button
            type="button"
            class="success p-0"
            data-toggle="modal"
            data-target="#change_price"
            style="all: unset"
          >
            <i class="ft-edit font-medium-3 mr-2"></i>
          </button>
          <a href="javascript:;" class="danger p-0">
            <i class="ft-trash-2 font-medium-3"></i>
          </a>
        </td>
      </tr>
    </tbody>
  </table>
</div>

src/templates/warehouse/orders/return_order.html
{% load static %}

<div class="ml-3">
  <div class="row">
    <h5>
      Customer
    </h5>
    <span class="ml-1 border-right pr-2">
        Jane Smith
    </span>
    <h5 class="pl-2">
        Return Order Number
      </h5>
      <span class="ml-1 border-right pr-3">
        R-ORD-0000759
    </span>
    <h5 class="pl-2">
        Order Number
    </h5>
    <span class="ml-1 pr-2">
        <a href="{% url 'proposal:order' %}">ORD-0000759</a>
    </span>
  </div>
</div>

<!-- Wizard Starts -->
<section id="icon-tabs">
  <div class="row">
    <div class="col-12">
      <div class="card p-0 m-0">
        <div class="card-content">
          <div class="card-body py-0">
            <form class="icons-tab-steps">

              <h6>Final Pick-up and Inspection</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./final_pick_up_inspection.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>In Transit - Inbound</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./in_transit_inbound.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>


              <h6>Warehouse Storage</h6>
              <fieldset class="mt-2" style="height: 70vh; overflow-y: auto; overflow-x: hidden">
                  {% include "./warehouse_storage.html" %}
                  {% include ".././file_upload.html" %}
                  {% include '.././comment_table.html' %}
              </fieldset>
              <form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


<script src="{% static 'app/js/ex-component-upload.min.js' %}"></script>